stages:
  - test
  - build
  - deploy

# tests:
#   script:
#     - pip install -r requirements.txt
#     - pip install -e .
#     - mv .env.development .env
#     - nosetests tests
#   tags: ["cgc-linter"]

# lint:
#   script:
#     - lint.py
#   tags: ["cgc-linter"]

docs:
  stage: build
  script: "generate_docs"
  tags: ["cgc-linter"]

build_images:
  stage: build
  only: ["master"]
  script:
  - cgc-build meister
  tags: ["docker-builder"]

production:
  stage: deploy
  only: ["master"]
  script:
  - docker tag meister 172.16.7.72/meister:stable
  - docker push 172.16.7.72/meister:stable
  environment: production
  tags: ["docker-builder"]
